seml:
    executable: kiez/experiment/seml_experiment.py
    name: kiez_seml_experiment
    output_dir: logs
    project_root_dir: /res_path/kiez/

slurm:
    experiments_per_job: 1
    sbatch_options:
        time: 0-01:00
        ntasks: 1
        cpus-per-task: 4
        partition: clara-job
        mem: 10G

fixed:
    n_neighbors: 50
    algorithm_params: {"n_candidates":100}
    leaf_size: 30
    p: 2
    query_samples: 15000
    target_samples: 15000
    metric: "euclidean"
    algorithm: "rptree"
    algorithm_params: {"n_candidates":100, "search_k":-1}

grid:
    dataset_tuple:
        type: choice
        options:
            - ("/res_path/output/results/MultiKE/D_W_15K_V1/721_5fold/1/", "/res_path/datasets/D_W_15K_V1/")
            - ("/res_path/output/results/MultiKE/D_W_15K_V2/721_5fold/1/", "/res_path/datasets/D_W_15K_V2/")
            - ("/res_path/output/results/MultiKE/D_Y_15K_V1/721_5fold/1/", "/res_path/datasets/D_Y_15K_V1/")
            - ("/res_path/output/results/MultiKE/D_Y_15K_V2/721_5fold/1/", "/res_path/datasets/D_Y_15K_V2/")
            - ("/res_path/output/results/MultiKE/EN_DE_15K_V1/721_5fold/1/", "/res_path/datasets/EN_DE_15K_V1/")
            - ("/res_path/output/results/MultiKE/EN_DE_15K_V2/721_5fold/1/", "/res_path/datasets/EN_DE_15K_V2/")
            - ("/res_path/output/results/MultiKE/EN_FR_15K_V1/721_5fold/1/", "/res_path/datasets/EN_FR_15K_V1/")
            - ("/res_path/output/results/MultiKE/EN_FR_15K_V2/721_5fold/1/", "/res_path/datasets/EN_FR_15K_V2/")
    hubness:
        type: choice
        options:
            - ("None",{})
            - ("csls",{})
            - ("mp",{"method":"normal"})
            - ("mp",{"method":"empiric"})
            - ("ls",{"method":"standard"})
            - ("ls",{"method":"nicdm"})
            - ("dsl",{"squared":False})

